// <auto-generated />
using System;
using MALanguageHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MALanguageHub.Migrations
{
    [DbContext(typeof(MALHdbcontext))]
    [Migration("20241126150418_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MALanguageHub.Models.Aboutus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_aboutus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software Engineer",
                            Title = "Software"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.Contactus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_contactus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "Kotli Azad Kashmir",
                            Address2 = "Islamabad Pakistan",
                            EmailAddress1 = "info@gmail.com",
                            EmailAddress2 = "contact@malanguagehub.com",
                            Facebook = "https://www.facebook.com/muhammad.naseer039",
                            Instagram = "https://www.facebook.com/muhammad.naseer039",
                            PhoneNumber = "923425464039",
                            TikTok = "https://www.facebook.com/muhammad.naseer039",
                            WhatsappNumber = "923425464039"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AllocatedTeacher")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("tbl_courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllocatedTeacher = 1,
                            Description = "Description for Course 1",
                            Duration = "2 Month",
                            StartingDate = new DateTime(2024, 11, 26, 20, 4, 18, 633, DateTimeKind.Local).AddTicks(5156),
                            Status = "Available",
                            Title = "Course 1"
                        },
                        new
                        {
                            Id = 2,
                            AllocatedTeacher = 1,
                            Description = "Description for Course 2",
                            Duration = "2 Month",
                            StartingDate = new DateTime(2024, 11, 26, 20, 4, 18, 633, DateTimeKind.Local).AddTicks(5166),
                            Status = "Available",
                            Title = "Course 2"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("tbl_home");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "I am Software Engineer",
                            Title = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "I am Civil Engineer",
                            Title = "Civil Engineer"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tbl_login");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Muhammad Naseer",
                            Password = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.OurProfessionals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("FacebookLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("WhatsAppLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_ourprofessionals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "I am a BS Computer Science student",
                            FacebookLink = "https://www.facebook.com/muhammad.naseer039",
                            InstagramLink = "https://www.facebook.com/muhammad.naseer039",
                            LinkedInLink = "https://www.facebook.com/muhammad.naseer039",
                            Title = "Muhammad Naseer",
                            WhatsAppLink = "https://www.facebook.com/muhammad.naseer039"
                        },
                        new
                        {
                            Id = 2,
                            Description = "I am a BS Information student",
                            FacebookLink = "https://www.facebook.com/muhammad.naseer039",
                            InstagramLink = "https://www.facebook.com/muhammad.naseer039",
                            LinkedInLink = "https://www.facebook.com/muhammad.naseer039",
                            Title = "Muhammad Insram",
                            WhatsAppLink = "https://www.facebook.com/muhammad.naseer039"
                        },
                        new
                        {
                            Id = 3,
                            Description = "I am a BS Mathematics student",
                            FacebookLink = "https://www.facebook.com/muhammad.naseer039",
                            InstagramLink = "https://www.facebook.com/muhammad.naseer039",
                            LinkedInLink = "https://www.facebook.com/muhammad.naseer039",
                            Title = "Muhammad Sultan",
                            WhatsAppLink = "https://www.facebook.com/muhammad.naseer039"
                        },
                        new
                        {
                            Id = 4,
                            Description = "I am a BS English student",
                            FacebookLink = "https://www.facebook.com/muhammad.naseer039",
                            InstagramLink = "https://www.facebook.com/muhammad.naseer039",
                            LinkedInLink = "https://www.facebook.com/muhammad.naseer039",
                            Title = "Muhammad Ali",
                            WhatsAppLink = "https://www.facebook.com/muhammad.naseer039"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LogoFavicon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MALanguageHub"
                        });
                });

            modelBuilder.Entity("MALanguageHub.Models.StudentReviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("tbl_studentreviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Student",
                            Name = "Insram",
                            Review = "Great learning experience!"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Student",
                            Name = "Naseer",
                            Review = "Great learning experience!"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Student",
                            Name = "Sultan",
                            Review = "Great learning experience!"
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Student",
                            Name = "Ali",
                            Review = "Great learning experience!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
